### ISSUE TITLE
Openshift user can't create new apps in ArgoCD

### ISSUE THREAD

**Issue by tgubeli** [LOT-assets/gitops-testdrive#1]
Only the 'admin' user has enough privileges in ArgoCD for creating new Applications. The [gitops-testdrive](https://github.com/LOT-assets/gitops-testdrive)/[docs](https://github.com/LOT-assets/gitops-testdrive/tree/main/docs)/[deploying-apps.md](https://github.com/LOT-assets/gitops-testdrive/tree/main/docs/deploying-apps.md) should say 'Login with Admin user' only.

**Comment by jcepedav** [comment]
Carlos adjusted the deployment method to deploy the RoleBinding and the ArgoCD groups. ArgoCD Application of bootstrapping deploys all components automatically and can be parametrized via overriding of ArgoCD on main ArgoCD.
